import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const $ = id => document.getElementById(id);
const finite = v => Number.isFinite(Number(v));
const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
const flat = v => { const a=[]; (function f(x){Array.isArray(x)?x.forEach(f):a.push(x)})(v); return a; };
const API = `${location.protocol==='file:'?'http:':location.protocol}//${location.hostname||'127.0.0.1'}:8000`;
const LABEL={temperature:'Temperature',temperature_anomaly:'SST anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',chlorophyll:'Chlorophyll'};
const DEPTH_NAMES=new Set(['depth','deptht','depthu','depthv','depthw','lev','level','z']);
const LAT_NAMES=new Set(['latitude','lat']);
const LON_NAMES=new Set(['longitude','lon']);
const PAL={
  temperature:[[0x071b8f,0],[0x075cff,.15],[0x00c6ff,.32],[0x00e79a,.48],[0xfff000,.62],[0xff6b00,.8],[0xb40000,1]],
  temperature_anomaly:[[0x06349e,0],[0x4b9fe8,.25],[0xffffff,.5],[0xffa060,.75],[0xb60018,1]],
  salinity:[[0x071d9b,0],[0x00a6ff,.2],[0x00d49a,.42],[0xb8e52e,.68],[0xffe600,1]],
  sea_level:[[0x102caa,0],[0x00a9ff,.25],[0x26d08b,.5],[0xffd21a,.75],[0xd40000,1]],
  chlorophyll:[[0xf7fff0,0],[0xb7ef59,.2],[0x42c83e,.45],[0x078d38,.72],[0x003d20,1]],
  fallback:[[0x071b8f,0],[0x00cfff,.25],[0xfff000,.5],[0xff6a00,.75],[0xb40000,1]]
};
const S={scene:null,camera:null,renderer:null,controls:null,root:null,geometry:null,catalog:[],times:[],ti:0,active:'temperature',domain:null,descriptor:null,range:null,land:null,coast:null,seabed:null,water:null,waterGroups:[],surface:null,currents:null,depthMode:'volume',sliceDepth:0,depthEx:10,request:0,playing:false,lastPlay:0,raycaster:new THREE.Raycaster(),mouse:new THREE.Vector2()};

async function get(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.json();}
async function getStatic(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.json();}
function status(t,type='ok'){$('status').textContent=t;$('statusDot').className=type==='error'?'error':type==='busy'?'busy':'';}
function fail(e){console.error(e);$('loading').classList.add('hidden');$('fatalText').textContent=e?.message||String(e);$('fatal').classList.add('show');status(`Viewer failed · ${e?.message||e}`,'error');}
function clear(o){if(!o)return;o.traverse(x=>{x.geometry?.dispose();if(x.material){if(Array.isArray(x.material))x.material.forEach(m=>m.dispose());else x.material.dispose()}});o.parent?.remove(o);}
function percentile(a,p){if(!a.length)return NaN;const v=[...a].sort((x,y)=>x-y),q=(v.length-1)*p,i=Math.floor(q),j=Math.ceil(q);return v[i]+(v[j]-v[i])*(q-i);}
function color(value){const stops=PAL[S.active]||PAL.fallback;const t=clamp((Number(value)-S.range.lo)/(S.range.hi-S.range.lo||1),0,1);let a=stops[0],b=stops.at(-1);for(let i=0;i<stops.length-1;i++)if(t<=stops[i+1][1]){a=stops[i];b=stops[i+1];break;}const u=(t-a[1])/(b[1]-a[1]||1);const ar=(a[0]>>16)&255,ag=(a[0]>>8)&255,ab=a[0]&255,br=(b[0]>>16)&255,bg=(b[0]>>8)&255,bb=b[0]&255;return new THREE.Color((ar+(br-ar)*u)/255,(ag+(bg-ag)*u)/255,(ab+(bb-ab)*u)/255);}
function logicalDomain(m){const c=m.coordinates||{},lat=c.latitude||c.lat,lon=c.longitude||c.lon;if(!lat||!lon)throw Error(`No latitude/longitude in ${m.file}`);return{lat:[+lat.min,+lat.max],lon:[+lon.min,+lon.max]};}
function varMeta(m,n){return(m.variables||[]).find(v=>v.name===n)}
function chooseStride(m,n){const v=varMeta(m,n),d=v?.dimensions||[],s=v?.shape||[];let li=-1,xi=-1;d.forEach((x,i)=>{if(LAT_NAMES.has(x))li=i;if(LON_NAMES.has(x))xi=i});const grid=li>=0&&xi>=0?(s[li]||1)*(s[xi]||1):1;return grid>3600?5:grid>2200?4:grid>1200?3:grid>600?2:1;}
function parseField(packet){const dims=packet.dimensions||[],shape=packet.shape||[],c=packet.coordinates||{};const latName=dims.find(d=>LAT_NAMES.has(d)),lonName=dims.find(d=>LON_NAMES.has(d)),depthName=dims.find(d=>DEPTH_NAMES.has(d));if(!latName||!lonName)throw Error('Field has no latitude/longitude dimensions');const lat=(c[latName]||[]).map(Number),lon=(c[lonName]||[]).map(Number),dep=depthName?(c[depthName]||[]).map(Number):[0],raw=flat(packet.data||[]).map(Number);const st=new Array(shape.length);let acc=1;for(let i=shape.length-1;i>=0;i--){st[i]=acc;acc*=shape[i];}const li=dims.indexOf(latName),xi=dims.indexOf(lonName),zi=depthName?dims.indexOf(depthName):-1;const yo=lat.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),xo=lon.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),zo=dep.map((v,i)=>[Math.abs(v),i]).sort((a,b)=>a[0]-b[0]),w=xo.length,h=yo.length,z=zo.length,values=new Float32Array(w*h*z);values.fill(NaN);const idx=(x,y,k)=>{let p=0;for(let d=0;d<dims.length;d++){let q=0;if(d===xi)q=x;else if(d===li)q=y;else if(d===zi)q=k;p+=q*st[d];}return p;};const valid=[];for(let k=0;k<z;k++)for(let j=0;j<h;j++)for(let i=0;i<w;i++){const v=Number(raw[idx(xo[i][1],yo[j][1],zi<0?0:zo[k][1])]);values[k*w*h+j*w+i]=v;if(finite(v))valid.push(v);}return{width:w,height:h,depth:z,lon:xo.map(x=>x[0]),lat:yo.map(x=>x[0]),levels:zo.map(x=>x[0]),values,valid,depthDependent:z>1};}
function project(lon,lat){const b=S.geometry?.bounds||[84,93,16,24],midLat=(b[2]+b[3])/2,klat=111.32,klon=111.32*Math.cos(midLat*Math.PI/180),midLon=(b[0]+b[1])/2;return[(Number(lon)-midLon)*klon,(Number(lat)-midLat)*klat];}
function layerY(depthM){return -Number(depthM)*S.depthEx/1000;}
function terrainDepthAt(lon,lat){const t=S.geometry?.terrain;if(!t?.x?.length||!t?.y?.length)return 0;const p=project(lon,lat),nx=t.x.length,ny=t.y.length;const ix=clamp(Math.round((p[0]-t.x[0])/((t.x[nx-1]-t.x[0])||1)*(nx-1)),0,nx-1),iy=clamp(Math.round((p[1]-t.y[0])/((t.y[ny-1]-t.y[0])||1)*(ny-1)),0,ny-1),d=Number((t.rawDepthKm[iy]||[])[ix]);return finite(d)?Math.max(0,d*1000):0;}
function cellBounds(a,i){if(a.length===1)return[a[0]-.025,a[0]+.025];if(i===0)return[a[0]-(a[1]-a[0])/2,(a[0]+a[1])/2];if(i===a.length-1)return[(a[i-1]+a[i])/2,a[i]+(a[i]-a[i-1])/2];return[(a[i-1]+a[i])/2,(a[i]+a[i+1])/2];}
function lineGeometry(lines,y=0){const p=[];for(const l of lines||[])for(let i=0;i<l.length-1;i++)p.push(l[i][0],y,l[i][1],l[i+1][0],y,l[i+1][1]);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));return g;}
function polygonGeometry(parts,y=0){const p=[],idx=[];let base=0;for(const part of parts||[]){for(const v of part.vertices||[])p.push(Number(v[0]),y,Number(v[1]));for(const t of part.triangles||[])idx.push(base+t[0],base+t[1],base+t[2]);base+=(part.vertices||[]).length;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(idx);return g;}
function drawLand(){clear(S.land);clear(S.coast);const g=S.geometry;if(!g)return;const lg=polygonGeometry([...(g.land||[]),...(g.islands||[])],.08);S.land=new THREE.Mesh(lg,new THREE.MeshBasicMaterial({color:0x4e984f,side:THREE.DoubleSide}));S.root.add(S.land);const cg=lineGeometry([...(g.coast||[]),...(g.landBoundary||[]),...(g.islandCoast||[])],.11);S.coast=new THREE.LineSegments(cg,new THREE.LineBasicMaterial({color:0x163f22}));S.root.add(S.coast);}
function drawSeabed(){clear(S.seabed);const t=S.geometry?.terrain;if(!t?.x?.length||!t?.y?.length)return;const w=t.x.length,h=t.y.length,p=[],map=new Int32Array(w*h);map.fill(-1);for(let j=0;j<h;j++)for(let i=0;i<w;i++){const d=Number((t.rawDepthKm[j]||[])[i]);if(!finite(d))continue;map[j*w+i]=p.length/3;p.push(t.x[i],-Math.max(0,d)*S.depthEx,t.y[j]);}const idx=[];for(let j=0;j<h-1;j++)for(let i=0;i<w-1;i++){const a=map[j*w+i],b=map[j*w+i+1],c=map[(j+1)*w+i],d=map[(j+1)*w+i+1];if(a>=0&&b>=0&&c>=0&&d>=0)idx.push(a,c,b,b,c,d);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(idx);g.computeVertexNormals();S.seabed=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x6f4b28,roughness:1,side:THREE.DoubleSide}));S.root.add(S.seabed);}
function drawSurface(){clear(S.surface);const o=S.geometry?.ocean||[];if(!o.length)return;S.surface=new THREE.Mesh(polygonGeometry(o,.16),new THREE.MeshPhysicalMaterial({color:0x0879c5,transparent:true,opacity:.09,roughness:.06,metalness:.02,depthWrite:false,side:THREE.DoubleSide}));S.root.add(S.surface);}
function buildInstances(cells,opacity=.16){if(!cells.length)return null;const box=new THREE.BoxGeometry(1,1,1),mat=new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity,depthWrite:false,side:THREE.DoubleSide}),mesh=new THREE.InstancedMesh(box,mat,cells.length),dummy=new THREE.Object3D();for(let i=0;i<cells.length;i++){const c=cells[i];dummy.position.set(c.x,c.y,c.z);dummy.scale.set(Math.max(.001,c.sx),Math.max(.02,c.sy),Math.max(.001,c.sz));dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);mesh.setColorAt(i,color(c.value));}mesh.instanceMatrix.needsUpdate=true;mesh.instanceColor.needsUpdate=true;mesh.userData.cells=cells;mesh.userData.isWater=true;box.dispose();return mesh;}
function buildWater(d){clear(S.water);S.waterGroups=[];S.water=new THREE.Group();const w=d.width,h=d.height,sp=w*h,levels=d.levels;const valueAt=(k,i,j)=>{let v=d.values[k*sp+j*w+i];if(finite(v))return v;for(let dk=1;dk<d.depth;dk++){const a=k-dk,b=k+dk;if(a>=0&&(v=d.values[a*sp+j*w+i])!==undefined&&finite(v))return v;if(b<d.depth&&(v=d.values[b*sp+j*w+i])!==undefined&&finite(v))return v;}return NaN;};for(let k=0;k<d.depth;k++){const top=k===0?0:levels[k-1],source=levels[k],cells=[];for(let j=0;j<h;j++)for(let i=0;i<w;i++){const v=valueAt(k,i,j);if(!finite(v))continue;const xb=cellBounds(d.lon,i),zb=cellBounds(d.lat,j),bottom= k===d.depth-1?Math.max(source,terrainDepthAt(d.lon[i],d.lat[j])):source,th=bottom-top;if(!(th>0.05))continue;const x0=project(xb[0],d.lat[j])[0],x1=project(xb[1],d.lat[j])[0],z0=project(d.lon[i],zb[0])[1],z1=project(d.lon[i],zb[1])[1];cells.push({x:(x0+x1)/2,z:(z0+z1)/2,sx:Math.abs(x1-x0),sz:Math.abs(z1-z0),y:layerY(top+th/2),sy:Math.max(.08,Math.abs(layerY(th))),value:Number(v),lon:d.lon[i],lat:d.lat[j],depth:top+th/2});}const mesh=buildInstances(cells,k===0?.28:.18);if(mesh)S.water.add(mesh);S.waterGroups.push({depth:top,mesh});}S.root.add(S.water);updateWaterVisibility();}
function updateWaterVisibility(){for(const g of S.waterGroups)if(g.mesh)g.mesh.visible=S.depthMode==='volume'||Math.abs(g.depth-S.sliceDepth)<=Math.max(2,(S.descriptor?.levels?.at(-1)||1)*.025);}
function drawCurrents(){clear(S.currents);S.currents=null;if(S.active!=='currents')return;const q=new URLSearchParams({stride:'5'});if(S.times[S.ti])q.set('time',S.times[S.ti]);q.set('depth',String(S.depthMode==='slice'?S.sliceDepth:0));get(`/ocean/current-grid?${q}`).then(data=>{const lat=(data.latitude||[]).map(Number),lon=(data.longitude||[]).map(Number),u=data.u||[],v=data.v||[],p=[];let max=0;for(let j=0;j<lat.length;j++)for(let i=0;i<lon.length;i++){const a=Number(u[j]?.[i]),b=Number(v[j]?.[i]);if(finite(a)&&finite(b))max=Math.max(max,Math.hypot(a,b));}max=Math.max(max,1e-9);for(let j=0;j<lat.length;j++)for(let i=0;i<lon.length;i++){const a=Number(u[j]?.[i]),b=Number(v[j]?.[i]);if(!finite(a)||!finite(b))continue;const p0=project(lon[i],lat[j]),L=8+18*Math.hypot(a,b)/max,dx=a/max*L,dz=b/max*L,x=p0[0],z=p0[1],ex=x+dx,ez=z+dz; p.push(x,.42,z,ex,.42,ez);const ang=Math.atan2(dz,dx),ah=Math.min(5,L*.25);p.push(ex,.42,ez,ex-ah*Math.cos(ang-.55),.42,ez-ah*Math.sin(ang-.55),ex,.42,ez,ex-ah*Math.cos(ang+.55),.42,ez-ah*Math.sin(ang+.55));}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));S.currents=new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:0x073c68,transparent:true,opacity:.9}));S.root.add(S.currents);}).catch(e=>console.warn('Currents:',e));}
function drawStatic(){drawLand();drawSeabed();drawSurface();}
function rebuild(){drawStatic();if(S.descriptor)buildWater(S.descriptor);}
async function loadGeometry(){S.geometry=await getStatic('geometry.json');if(!S.geometry?.land||!S.geometry?.terrain)throw Error('geometry.json is missing land or GEBCO terrain data');}
async function loadField(){const token=++S.request,item=S.catalog.find(x=>x.id===S.active);if(!item?.available){status(`${LABEL[S.active]} unavailable`,'error');return;}status(`Loading ${LABEL[S.active]}…`,'busy');const m=await get(`/metadata/${encodeURIComponent(item.file)}`);S.domain=logicalDomain(m);const qs=new URLSearchParams({file:item.file,variable:item.variable,lat_min:S.domain.lat[0],lat_max:S.domain.lat[1],lon_min:S.domain.lon[0],lon_max:S.domain.lon[1],stride:chooseStride(m,item.variable)});if(S.times[S.ti]){qs.set('time_start',S.times[S.ti]);qs.set('time_end',S.times[S.ti]);}const packet=await get(`/data/region/array?${qs}`);if(token!==S.request)return;const d=parseField(packet);if(!d.valid.length)throw Error('No finite values returned');S.descriptor=d;let lo=percentile(d.valid,.01),hi=percentile(d.valid,.99);if(S.active==='temperature_anomaly'){const z=Math.max(Math.abs(lo),Math.abs(hi));lo=-z;hi=z;}if(!(hi>lo)){const e=Math.max(Math.abs(lo)*.02,1e-6);lo-=e;hi+=e;}S.range={lo,hi};clear(S.water);clear(S.currents);if(d.depthDependent){$('depthSection').classList.remove('hidden');$('depthMax').textContent=`${d.levels.at(-1).toFixed(0)} m`;$('depthSlider').max=String(d.levels.at(-1)||1);S.sliceDepth=clamp(S.sliceDepth,0,d.levels.at(-1)||0);$('depthSlider').value=String(S.sliceDepth);}else{$('depthSection').classList.add('hidden');S.sliceDepth=0;}$('legendLo').textContent=lo.toPrecision(5);$('legendHi').textContent=hi.toPrecision(5);$('legendNote').textContent=`1–99 percentile · ${d.valid.length.toLocaleString()} finite samples`;rebuild();drawCurrents();updateDepthBadge();status(`${LABEL[S.active]} · ${d.depthDependent?d.depth:1} depth levels`);$('loading').classList.add('hidden');}
function updateDepthBadge(){const t=S.depthMode==='volume'?'Volume':`${S.sliceDepth.toFixed(0)} m`;$('depthValue').textContent=t;$('depthBadge').textContent=t;}
function buildRenderer(){const c=$('renderCanvas');S.renderer=new THREE.WebGLRenderer({canvas:c,antialias:true,powerPreference:'high-performance'});S.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));S.renderer.setSize(innerWidth,innerHeight,false);S.renderer.setClearColor(0xaedce6,1);S.renderer.outputColorSpace=THREE.SRGBColorSpace;S.scene=new THREE.Scene();S.camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,5000);S.controls=new OrbitControls(S.camera,c);S.controls.enableDamping=true;S.controls.screenSpacePanning=true;S.controls.minDistance=10;S.controls.maxDistance=2500;S.root=new THREE.Group();S.scene.add(S.root);S.scene.add(new THREE.HemisphereLight(0xd7f5ff,0x654b2e,1.35),new THREE.DirectionalLight(0xffffff,1.25));}
function fitCamera(){if(!S.geometry?.bounds)return;const b=S.geometry.bounds,mid=(b[2]+b[3])/2,w=(b[1]-b[0])*111.32*Math.cos(mid*Math.PI/180),h=(b[3]-b[2])*111.32,d=Math.max(60,(S.geometry.terrain?.maxDepthKm||1)*S.depthEx),r=Math.max(w,h,d,100);S.camera.position.set(r*.92,r*.62,r*1.04);S.controls.target.set(0,-Math.min(d*.2,r*.3),0);S.camera.near=.1;S.camera.far=r*25;S.camera.updateProjectionMatrix();S.controls.update();}
function setView(v){if(!S.geometry?.bounds)return;const b=S.geometry.bounds,mid=(b[2]+b[3])/2,w=(b[1]-b[0])*111.32*Math.cos(mid*Math.PI/180),h=(b[3]-b[2])*111.32,d=Math.max(80,(S.geometry.terrain?.maxDepthKm||1)*S.depthEx),r=Math.max(w,h,d);if(v==='top')S.camera.position.set(0,r*1.55,.01);else if(v==='profile')S.camera.position.set(r*1.35,-r*.04,0);else if(v==='under')S.camera.position.set(0,-r*.7,r*.8);else S.camera.position.set(r,r*.6,r);S.controls.target.set(0,v==='top'?0:-Math.min(d*.2,r*.3),0);S.controls.update();}
function updateTimeline(){const raw=S.times[S.ti];if(!raw)return;const d=new Date(raw);$('timeValue').textContent=d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'});$('timeRaw').textContent=d.toISOString();$('timeCount').textContent=`${S.ti+1}/${S.times.length}`;}
function setupUI(){$('vars').addEventListener('click',e=>{const b=e.target.closest('[data-field]');if(!b||b.disabled)return;document.querySelectorAll('[data-field]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.active=b.dataset.field;loadField().catch(fail);});$('depthMode').addEventListener('click',e=>{const b=e.target.closest('[data-depth-mode]');if(!b)return;document.querySelectorAll('#depthMode button').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.depthMode=b.dataset.depthMode;updateWaterVisibility();updateDepthBadge();});$('depthSlider').addEventListener('input',e=>{S.sliceDepth=Number(e.target.value);updateWaterVisibility();updateDepthBadge();});$('exaggeration').addEventListener('input',e=>{S.depthEx=Number(e.target.value);$('exagValue').textContent=`${S.depthEx}×`;rebuild();fitCamera();});document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));if(b.dataset.view)b.classList.add('active');if(b.dataset.view)setView(b.dataset.view);}));$('reset').addEventListener('click',fitCamera);$('fullscreen').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.());$('play').addEventListener('click',()=>{S.playing=!S.playing;$('play').textContent=S.playing?'PAUSE':'PLAY';S.lastPlay=0;});$('timeSlider').addEventListener('input',e=>{S.ti=Number(e.target.value);updateTimeline();loadField().catch(fail);});$('closeReadout').addEventListener('click',()=>$('readout').classList.add('hidden'));$('renderCanvas').addEventListener('pointerdown',onCanvasClick);addEventListener('resize',()=>{S.camera.aspect=innerWidth/innerHeight;S.camera.updateProjectionMatrix();S.renderer.setSize(innerWidth,innerHeight,false);});}
function makeVariableButtons(){const box=$('vars');box.innerHTML='';for(const x of S.catalog){const b=document.createElement('button');b.className=`field ${x.id===S.active?'active':''}`;b.dataset.field=x.id;b.disabled=!x.available;b.innerHTML=`<b>${x.label||LABEL[x.id]}</b><small>${x.units||'—'}</small><i></i>`;box.appendChild(b);}}
async function showPoint(lat,lon,depth=0){try{const qs=new URLSearchParams({latitude:lat,longitude:lon});if(S.times[S.ti])qs.set('time',S.times[S.ti]);const d=await get(`/ocean/point?${qs}`);$('coords').textContent=`${lat.toFixed(4)}° N · ${lon.toFixed(4)}° E · ${depth.toFixed(0)} m`;$('readoutGrid').innerHTML='';for(const x of d.values||[]){if(!x.available)continue;let v=x.value;if(v&&typeof v==='object'&&!Array.isArray(v)){const a=Object.values(v).filter(finite).map(Number);v=a.length?Math.hypot(...a):'—';}if(!finite(v))v='—';const c=document.createElement('div');c.className='readoutCard';c.innerHTML=`<b>${x.label}</b><strong>${typeof v==='number'?v.toFixed(4):v}</strong><small>${x.units||'—'}</small>`;$('readoutGrid').appendChild(c);}$('readoutTime').textContent=S.times[S.ti]?new Date(S.times[S.ti]).toISOString():'—';$('readout').classList.remove('hidden');}catch(e){console.warn('Point:',e);}}
function onCanvasClick(e){const r=$('renderCanvas').getBoundingClientRect();S.mouse.x=((e.clientX-r.left)/r.width)*2-1;S.mouse.y=-((e.clientY-r.top)/r.height)*2+1;S.raycaster.setFromCamera(S.mouse,S.camera);const targets=[];S.water?.traverse(o=>{if(o.userData?.isWater)targets.push(o);});const hits=S.raycaster.intersectObjects(targets,false);if(!hits.length)return;const h=hits[0],c=h.object.userData.cells?.[h.instanceId];if(c)showPoint(c.lat,c.lon,c.depth);}
function loop(t=0){requestAnimationFrame(loop);if(S.playing&&S.times.length>1&&t-S.lastPlay>700){S.lastPlay=t;S.ti=(S.ti+1)%S.times.length;$('timeSlider').value=String(S.ti);updateTimeline();loadField().catch(fail);}S.controls?.update();S.renderer?.render(S.scene,S.camera);}
async function init(){buildRenderer();setupUI();status('Loading geometry…','busy');await loadGeometry();drawStatic();fitCamera();const [catalog,timeline]=await Promise.all([get('/ocean/catalog'),get('/ocean/time')]);S.catalog=catalog.variables||[];S.times=timeline.values||[];makeVariableButtons();$('timeSlider').max=String(Math.max(0,S.times.length-1));$('timeSlider').value='0';updateTimeline();await loadField();}
init().catch(fail);loop();
