import json


def render(data):
    payload = json.dumps(data, separators=(",", ":"))
    html = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>SolvX — Bay of Bengal 3D</title>
<style>
*{box-sizing:border-box}html,body,#app{margin:0;width:100%;height:100%;overflow:hidden;background:#ffffff}body{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#dcebf0}#app{position:fixed;inset:0}canvas{display:block;width:100%!important;height:100%!important}
#topbar{position:absolute;top:16px;left:16px;right:16px;z-index:10;display:flex;justify-content:space-between;pointer-events:none}.brand,.toolbar,.panel,.hint,.readout{background:rgba(7,21,28,.78);border:1px solid rgba(157,211,222,.18);box-shadow:0 12px 38px rgba(0,0,0,.22);backdrop-filter:blur(15px)}.brand{padding:10px 14px;border-radius:12px;pointer-events:auto}.brand b{display:block;font-size:13px;letter-spacing:.15em}.brand small{display:block;margin-top:3px;color:#8ca8af;font-size:8px}.toolbar{display:flex;gap:4px;padding:5px;border-radius:12px;pointer-events:auto}.btn{border:0;background:transparent;color:#91aab1;border-radius:8px;padding:9px 11px;font-size:9px;letter-spacing:.09em;cursor:pointer}.btn:hover{background:rgba(120,190,205,.1);color:#dff6fb}.btn.active{background:#0e3440;color:#b9edf5;box-shadow:inset 0 0 0 1px #3c8795}
#panel{position:absolute;top:84px;right:16px;width:310px;padding:15px;border-radius:14px;z-index:11;display:none}.panel-show{display:block!important}.panel h3{margin:0 0 12px;font-size:11px;letter-spacing:.12em;text-transform:uppercase}.section{padding:11px 0;border-top:1px solid rgba(157,211,222,.12)}.section:first-of-type{border-top:0;padding-top:0}.section-title{font-size:9px;color:#78939a;letter-spacing:.09em;text-transform:uppercase;margin-bottom:9px}.layers{display:grid;grid-template-columns:1fr 1fr;gap:6px}.layer{display:flex;align-items:center;gap:7px;padding:8px;border:1px solid rgba(157,211,222,.12);border-radius:8px;background:rgba(13,35,44,.8);color:#a9c0c5;font-size:9px;cursor:pointer}.layer.off{opacity:.4}.dot{width:7px;height:7px;border-radius:50%;background:#2c8296}.layer[data-g="surface"] .dot{background:#62c4d1}.layer[data-g="terrain"] .dot{background:#a77b51}.layer[data-g="land"] .dot{background:#557b55}.layer[data-g="eez"] .dot{background:#d39a2f}.layer[data-g="base"] .dot{background:#775640}.range-row{display:flex;align-items:center;gap:9px}.range-row input{width:100%}.value{min-width:42px;text-align:right;font-size:9px;color:#b5e7ed}.depth-note{font-size:8px;color:#829da4;line-height:1.5;margin-top:6px}.legend-item{display:flex;align-items:center;gap:8px;margin:7px 0;font-size:9px;color:#9ab1b7}.sw{width:22px;height:4px;border-radius:3px;display:inline-block}
#hint{position:absolute;left:16px;bottom:16px;padding:8px 11px;border-radius:9px;color:#819ba2;font-size:8px;z-index:8}#readout{position:absolute;right:16px;bottom:16px;padding:8px 11px;border-radius:9px;color:#91aeb5;font-size:8px;z-index:8}.loading{position:absolute;inset:0;background:#ffffff;display:grid;place-items:center;z-index:50;text-align:center}.loading b{display:block;font-size:20px;letter-spacing:.16em}.loading span{display:block;margin-top:6px;font-size:9px;color:#78939a;letter-spacing:.08em}
@media(max-width:760px){#topbar{top:8px;left:8px;right:8px}.brand small{display:none}.toolbar .btn{padding:9px 8px}.toolbar .btn:nth-child(4){display:none}#panel{top:70px;right:8px;width:calc(100vw - 16px)}#hint{left:8px;bottom:8px}#readout{right:8px;bottom:8px}}
</style></head><body><div id="app"><div id="load" class="loading"><div><b>SOLVX</b><span>BUILDING DEPTH-STRATIFIED OCEAN</span></div></div>
<div id="topbar"><div class="brand"><b>SOLVX</b><small>BAY OF BENGAL · GEBCO BATHYMETRY</small></div><div class="toolbar"><button class="btn active" data-v="overview">3D</button><button class="btn" data-v="top">TOP</button><button class="btn" data-v="profile">PROFILE</button><button class="btn" data-v="under">UNDER</button><button class="btn" id="layersBtn">LAYERS</button><button class="btn" id="fullBtn">FULLSCREEN</button></div></div>
<div id="panel" class="panel"><h3>Ocean visualization</h3><div class="section"><div class="section-title">Layers</div><div class="layers"><button class="layer" data-g="ocean"><i class="dot"></i>Ocean strata</button><button class="layer" data-g="surface"><i class="dot"></i>Water surface</button><button class="layer" data-g="particles"><i class="dot"></i>Suspended particles</button><button class="layer" data-g="terrain"><i class="dot"></i>Seabed</button><button class="layer" data-g="land"><i class="dot"></i>Land mass</button><button class="layer" data-g="coast"><i class="dot"></i>Coastlines</button><button class="layer" data-g="eez"><i class="dot"></i>EEZ boundary</button><button class="layer" data-g="base"><i class="dot"></i>Geological base</button></div></div><div class="section"><div class="section-title">Vertical exaggeration</div><div class="range-row"><input id="depth" type="range" min="1" max="100" step="1" value="70"><span id="depthVal" class="value">70×</span></div><div id="depthNote" class="depth-note"></div></div><div class="section"><div class="section-title">Data-ready depth strata</div><div class="depth-note">0–50 m · surface / light blue<br>50–200 m · shallow / cyan-blue<br>200–1000 m · intermediate / blue<br>1000–3000 m · deep / dark blue<br>3000+ m · abyssal / near-black blue</div></div><div class="section"><div class="section-title">Visual key</div><div class="legend-item"><i class="sw" style="background:#62c4d1"></i>Sunlit surface</div><div class="legend-item"><i class="sw" style="background:#176176"></i>Shallow water</div><div class="legend-item"><i class="sw" style="background:#0b3448"></i>Deep water</div><div class="legend-item"><i class="sw" style="background:#061722"></i>Abyssal water</div><div class="legend-item"><i class="sw" style="background:#a77b51"></i>GEBCO seabed</div></div></div>
<div id="hint" class="hint">Drag orbit · Right/Shift drag pan · Wheel zoom · 1–4 views · R reset</div><div id="readout" class="readout">GEBCO · depth-stratified ocean · particles active</div></div>
<script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/"}}</script>
<script type="module">
import * as THREE from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const D=__PAYLOAD__;const scene=new THREE.Scene();scene.background=new THREE.Color(0xffffff);scene.fog=new THREE.FogExp2(0x071923,.00055);
const cam=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,6000);cam.position.set(520,-650,480);const ren=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});ren.setPixelRatio(Math.min(devicePixelRatio,2));ren.setSize(innerWidth,innerHeight);ren.outputColorSpace=THREE.SRGBColorSpace;ren.setClearColor(0xffffff);document.getElementById('app').appendChild(ren.domElement);
const ctl=new OrbitControls(cam,ren.domElement);ctl.enableDamping=true;ctl.dampingFactor=.055;ctl.screenSpacePanning=true;ctl.minDistance=30;ctl.maxDistance=2400;ctl.target.set(0,0,-30);
scene.add(new THREE.HemisphereLight(0x9bd8e2,0x17232a,1.25));const sun=new THREE.DirectionalLight(0xc9f5ff,2.5);sun.position.set(-350,-420,900);scene.add(sun);
const G={ocean:new THREE.Group(),surface:new THREE.Group(),particles:new THREE.Group(),terrain:new THREE.Group(),land:new THREE.Group(),coast:new THREE.Group(),eez:new THREE.Group(),base:new THREE.Group()};Object.values(G).forEach(g=>scene.add(g));
const mats={land:new THREE.MeshStandardMaterial({color:0x4e7651,roughness:.9}),side:new THREE.MeshStandardMaterial({color:0x654936,roughness:1}),bottom:new THREE.MeshStandardMaterial({color:0x5a402f,roughness:1}),coast:new THREE.LineBasicMaterial({color:0x9db9bc}),eez:new THREE.LineBasicMaterial({color:0xd39a2f}),bead:new THREE.MeshStandardMaterial({color:0xd39a2f,roughness:.4}),base:new THREE.MeshStandardMaterial({color:0x644936,roughness:1})};
let depthScale=70;
(function(){const xs=D.terrain.x,ys=D.terrain.y,raw=D.terrain.rawDepthKm,nx=xs.length,ny=ys.length,pos=new Float32Array(nx*ny*3),col=new Float32Array(nx*ny*3),ind=[];let max=0;for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const d=raw[j][i];if(Number.isFinite(d))max=Math.max(max,d)}D.terrain.maxRawDepthKm=max;for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const k=j*nx+i,o=k*3,d=raw[j][i],t=Number.isFinite(d)?Math.min(1,d/Math.max(1,max)):0;pos[o]=xs[i];pos[o+1]=ys[j];pos[o+2]=Number.isFinite(d)?-d*depthScale:0;col[o]=.68-.28*t;col[o+1]=.52-.23*t;col[o+2]=.34-.17*t}for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const a=j*nx+i,b=a+1,c=a+nx,d=c+1;if([raw[j][i],raw[j][i+1],raw[j+1][i],raw[j+1][i+1]].every(Number.isFinite))ind.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('color',new THREE.BufferAttribute(col,3));g.setIndex(ind);g.computeVertexNormals();const m=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.86,side:THREE.DoubleSide});const mesh=new THREE.Mesh(g,m);G.terrain.add(mesh);D._terrainMesh=mesh})();
function poly(p){if(p.vertices&&p.triangles&&p.triangles.length){const v=[],ix=[];p.vertices.forEach(q=>v.push(q[0],q[1],0));p.triangles.forEach(t=>ix.push(t[0],t[1],t[2]));const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(ix);g.computeVertexNormals();G.land.add(new THREE.Mesh(g,mats.land))}if(p.top&&p.top.length>1){const v=[],ix=[];for(let i=0;i<p.top.length-1;i++){const a=p.top[i],b=p.top[i+1],q=v.length/3;v.push(a[0],a[1],0,a[0],a[1],-1,b[0],b[1],0,b[0],b[1],-1);ix.push(q,q+2,q+1,q+2,q+3,q+1)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(ix);g.computeVertexNormals();G.land.add(new THREE.Mesh(g,mats.side))}if(p.vertices&&p.triangles&&p.triangles.length){const v=[],ix=[];p.vertices.forEach(q=>v.push(q[0],q[1],0));p.triangles.forEach(t=>ix.push(t[2],t[1],t[0]));const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(ix);g.computeVertexNormals();G.land.add(new THREE.Mesh(g,mats.bottom))}}D.land.forEach(poly);D.islands.forEach(poly);
function draw(parts,mat,z){parts.forEach(p=>{if(p.length<2)return;G.coast.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(p.map(x=>new THREE.Vector3(x[0],x[1],z))),mat))})}draw(D.coast,mats.coast,.03);draw(D.landBoundary,mats.coast,.04);draw(D.islandCoast,mats.coast,.05);D.eez.forEach(p=>{if(p.length>1)G.eez.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(p.map(x=>new THREE.Vector3(x[0],x[1],.08))),mats.eez))});const beadGeo=new THREE.SphereGeometry(2,10,7);D.eezBeads.forEach(p=>{const m=new THREE.Mesh(beadGeo,mats.bead);m.position.set(p[0],p[1],.12);G.eez.add(m)});
const W=(D.bounds[1]-D.bounds[0])*111.32*Math.cos(((D.bounds[2]+D.bounds[3])/2)*Math.PI/180),H=(D.bounds[3]-D.bounds[2])*111.32;const baseMesh=new THREE.Mesh(new THREE.BoxGeometry(W,H,1),mats.base);G.base.add(baseMesh);
// Real volumetric strata. Every grid cell gets its own top/bottom prism; this avoids the curtain artifact from the previous implementation.
const bands=[{name:'surface',lo:0,hi:.05,color:0x56c5d3,opacity:.20},{name:'shallow',lo:.05,hi:.2,color:0x16859b,opacity:.16},{name:'intermediate',lo:.2,hi:1,color:0x0d5870,opacity:.14},{name:'deep',lo:1,hi:3,color:0x08364d,opacity:.13},{name:'abyssal',lo:3,hi:9,color:0x041d2b,opacity:.16}];const bandMeshes=[];
function buildBand(b){const raw=D.terrain.rawDepthKm,nx=D.terrain.x.length,ny=D.terrain.y.length,pos=[],ix=[];for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const d00=raw[j][i],d10=raw[j][i+1],d01=raw[j+1][i],d11=raw[j+1][i+1];if(![d00,d10,d01,d11].every(Number.isFinite))continue;if(Math.max(d00,d10,d01,d11)<=b.lo)continue;const ds=[d00,d10,d11,d01],v=[];for(const d of ds)v.push(Math.min(b.lo,d),Math.min(b.hi,d));const q=pos.length/3;const X=[D.terrain.x[i],D.terrain.x[i+1],D.terrain.x[i+1],D.terrain.x[i]],Y=[D.terrain.y[j],D.terrain.y[j],D.terrain.y[j+1],D.terrain.y[j+1]];for(let k=0;k<4;k++){pos.push(X[k],Y[k],-v[k*2]*depthScale);pos.push(X[k],Y[k],-v[k*2+1]*depthScale)}ix.push(q,q+2,q+4,q,q+4,q+6,q+1,q+5,q+3,q+3,q+5,q+7,q,q+1,q+2,q+2,q+1,q+3,q+6,q+7,q+4,q+4,q+7,q+5)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(ix);g.computeVertexNormals();const m=new THREE.MeshPhysicalMaterial({color:b.color,transparent:true,opacity:b.opacity,roughness:.12,metalness:.0,transmission:.12,ior:1.33,depthWrite:false,side:THREE.DoubleSide});const mesh=new THREE.Mesh(g,m);mesh.renderOrder=10+bandMeshes.length;G.ocean.add(mesh);bandMeshes.push(mesh)}bands.forEach(buildBand);
// Dense but subtle suspended matter. Particles are placed only inside the GEBCO water column.
(function(){const n=2600,pp=new Float32Array(n*3),sz=new Float32Array(n),raw=D.terrain.rawDepthKm,nx=D.terrain.x.length,ny=D.terrain.y.length;for(let k=0;k<n;k++){const i=1+Math.floor(Math.random()*(nx-2)),j=1+Math.floor(Math.random()*(ny-2)),d=raw[j][i];if(!Number.isFinite(d)){k--;continue}const z=-Math.random()*Math.min(d,8)*depthScale*.92;pp[k*3]=D.terrain.x[i]+(Math.random()-.5)*8;pp[k*3+1]=D.terrain.y[j]+(Math.random()-.5)*8;pp[k*3+2]=z;sz[k]=.6+Math.random()*1.8}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pp,3));g.setAttribute('size',new THREE.BufferAttribute(sz,1));const m=new THREE.PointsMaterial({color:0x9fc8c8,size:1.5,transparent:true,opacity:.28,depthWrite:false,sizeAttenuation:true});G.particles.add(new THREE.Points(g,m))})();
// Water surface: transparent blue, moving micro-ripples and a second low-opacity highlight layer.
(function(){const sx=170,sy=130,pos=new Float32Array((sx+1)*(sy+1)*3),uv=new Float32Array((sx+1)*(sy+1)*2),ix=[];for(let j=0;j<=sy;j++)for(let i=0;i<=sx;i++){const k=j*(sx+1)+i;pos[k*3]=-W/2+W*i/sx;pos[k*3+1]=-H/2+H*j/sy;pos[k*3+2]=0;uv[k*2]=i/sx;uv[k*2+1]=j/sy}for(let j=0;j<sy;j++)for(let i=0;i<sx;i++){const a=j*(sx+1)+i,b=a+1,c=a+sx+1,d=c+1;ix.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('uv',new THREE.BufferAttribute(uv,2));g.setIndex(ix);const m=new THREE.MeshPhysicalMaterial({color:0x4eb5c5,transparent:true,opacity:.16,roughness:.04,metalness:.0,transmission:.22,ior:1.33,depthWrite:false,side:THREE.DoubleSide});const mesh=new THREE.Mesh(g,m);mesh.renderOrder=40;G.surface.add(mesh);D._surface=mesh;const rim=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:0x9ee9f0,transparent:true,opacity:.035,wireframe:true,depthWrite:false}));rim.renderOrder=41;G.surface.add(rim)})();
function updateDepth(){const mesh=D._terrainMesh,pos=mesh.geometry.attributes.position.array,raw=D.terrain.rawDepthKm,nx=D.terrain.x.length,ny=D.terrain.y.length;for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const o=(j*nx+i)*3,d=raw[j][i];pos[o+2]=Number.isFinite(d)?-d*depthScale:0}mesh.geometry.attributes.position.needsUpdate=true;mesh.geometry.computeVertexNormals();const deepest=-D.terrain.maxRawDepthKm*depthScale,bt=deepest-.8,bb=bt-D.baseExtra*depthScale;G.base.position.z=(bt+bb)/2;baseMesh.scale.z=bb-bt;const soil=Math.max(1.5,D.landThickness*depthScale);G.land.children.forEach(m=>{if(m.material===mats.side||m.material===mats.bottom)m.scale.z=soil});document.getElementById('depthVal').textContent=depthScale+'×';document.getElementById('depthNote').textContent=`GEBCO maximum ${D.terrain.maxRawDepthKm.toFixed(2)} km · vertical display ${ (D.terrain.maxRawDepthKm*depthScale).toFixed(0)} km · 5 water strata`}
updateDepth();
const views={overview:[520,-650,480],top:[0,0,1050],profile:[850,-30,170],under:[420,-520,-420]};let motion=null;function view(n){const v=views[n];motion={a:cam.position.clone(),b:new THREE.Vector3(...v),ta:ctl.target.clone(),tb:new THREE.Vector3(0,0,n==='under'?-80:-80),t:performance.now()};document.querySelectorAll('[data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v===n))}function reset(){view('overview')}function step(){if(!motion)return;const u=Math.min(1,(performance.now()-motion.t)/700),e=1-Math.pow(1-u,3);cam.position.lerpVectors(motion.a,motion.b,e);ctl.target.lerpVectors(motion.ta,motion.tb,e);if(u>=1)motion=null}
document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>view(b.dataset.v));document.getElementById('layersBtn').onclick=()=>document.getElementById('panel').classList.toggle('panel-show');document.getElementById('fullBtn').onclick=async()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();document.querySelectorAll('.layer').forEach(b=>b.onclick=()=>{const g=b.dataset.g;G[g].visible=!G[g].visible;b.classList.toggle('off',!G[g].visible)});document.getElementById('depth').oninput=e=>{depthScale=+e.target.value;updateDepth()};addEventListener('keydown',e=>{if(e.key==='1')view('overview');else if(e.key==='2')view('top');else if(e.key==='3')view('profile');else if(e.key==='4')view('under');else if(e.key.toLowerCase()==='r')reset();else if(e.key.toLowerCase()==='f')document.getElementById('fullBtn').click()});addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();ren.setSize(innerWidth,innerHeight)});
const t0=performance.now();document.getElementById('load').style.display='none';view('overview');(function loop(){requestAnimationFrame(loop);const t=(performance.now()-t0)*.001;const p=D._surface.geometry.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);p.setZ(i,.8*Math.sin(x*.045+t*.55)+.35*Math.cos(y*.06-t*.38)+.12*Math.sin((x+y)*.02+t*.25))}p.needsUpdate=true;D._surface.geometry.computeVertexNormals();G.particles.rotation.z=t*.0015;step();ctl.update();ren.render(scene,cam)})();
</script></body></html>'''
    return html.replace("__PAYLOAD__", payload)
